apiVersion: v2
name: aerospike
description: Aerospike helm charts
type: application
version: 1.3.2
appVersion: "1.16.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
